import assert from "node:assert/strict";
import test from "node:test";
import { normalizeLeadInput, LeadValidationError } from "../../packages/validation/src/lead-intake";
import { LeadIntakeService, type LeadBundleRepository } from "../../packages/crm/src/revenue-circuit";
import { conflicts, validateBookingSlot, type BookingSlot } from "../../packages/bookings/src/domain";
import { transitionProposal, validateProposalVersion, type ProposalVersion } from "../../packages/proposals/src/domain";
import { projectFromAcceptedProposal } from "../../packages/projects/src/domain";
import { processOutboxEvent } from "../../apps/worker/src/outbox-job";

const validRaw={name:"Ana Pérez",email:"ANA@EXAMPLE.COM",needs:"Congreso para 500 personas con audio y pantallas",serviceSlugs:["audio","video"],locale:"es-MX"};

test("normalizes public lead and rejects tenant/price authority",()=>{const x=normalizeLeadInput(validRaw);assert.equal(x.email,"ana@example.com");assert.throws(()=>normalizeLeadInput({...validRaw,tenantId:"evil"}),LeadValidationError);assert.throws(()=>normalizeLeadInput({...validRaw,price:1}),LeadValidationError)});
test("requires a contact channel and catches honeypot",()=>{assert.throws(()=>normalizeLeadInput({name:"Ana",needs:"Necesito producir un congreso grande"}),/required/);assert.throws(()=>normalizeLeadInput({...validRaw,website:"spam"}),/Honeypot/)});
test("unknown service is rejected before persistence",async()=>{let writes=0;const repo:LeadBundleRepository={findCompletedByIdempotency:async()=>null,createLeadBundle:async()=>{writes++;return{tenantId:"t",leadId:"l",requestId:"r",duplicate:false}}};const service=new LeadIntakeService(repo);await assert.rejects(()=>service.create({policy:{tenantId:"t",tenantSlug:"dos-a",allowedServiceSlugs:new Set(["audio"])},input:normalizeLeadInput({...validRaw,serviceSlugs:["not-real"]}),requestId:"r",payloadHash:"a".repeat(64),sourceChannel:"web"}));assert.equal(writes,0)});
test("idempotent replay returns existing durable lead",async()=>{let writes=0;const repo:LeadBundleRepository={findCompletedByIdempotency:async()=>({tenantId:"t",leadId:"existing",requestId:"old",duplicate:false}),createLeadBundle:async()=>{writes++;throw new Error("should not write")}};const service=new LeadIntakeService(repo);const r=await service.create({policy:{tenantId:"t",tenantSlug:"dos-a",allowedServiceSlugs:new Set(["audio","video"])},input:normalizeLeadInput(validRaw),requestId:"r",idempotencyKey:"request-123",payloadHash:"a".repeat(64),sourceChannel:"web"});assert.equal(r.leadId,"existing");assert.equal(r.duplicate,true);assert.equal(writes,0)});
test("notification failure never erases a durable lead",async()=>{const repo:LeadBundleRepository={findCompletedByIdempotency:async()=>null,createLeadBundle:async()=>({tenantId:"t",leadId:"l",requestId:"r",duplicate:false})};const service=new LeadIntakeService(repo,{notifyLeadCreated:async()=>{throw new Error("provider down")}});const r=await service.create({policy:{tenantId:"t",tenantSlug:"dos-a",allowedServiceSlugs:new Set(["audio","video"])},input:normalizeLeadInput(validRaw),requestId:"r",payloadHash:"a".repeat(64),sourceChannel:"web"});assert.equal(r.leadId,"l")});
test("booking conflict is tenant/resource/time scoped",()=>{const base:BookingSlot={id:"a",tenantId:"t1",type:"event",status:"confirmed",startsAt:"2026-09-01T10:00:00Z",endsAt:"2026-09-01T12:00:00Z",resourceKeys:["crew:audio"]};const candidate={...base,id:"b",startsAt:"2026-09-01T11:00:00Z",endsAt:"2026-09-01T13:00:00Z"};assert.equal(conflicts(candidate,[base]).length,1);assert.equal(conflicts({...candidate,tenantId:"t2"},[base]).length,0)});
test("tentative booking requires a valid future expiry",()=>{const slot:BookingSlot={id:"a",tenantId:"t",type:"event",status:"tentative",startsAt:"2026-09-02T10:00:00Z",endsAt:"2026-09-02T12:00:00Z",resourceKeys:[]};assert.throws(()=>validateBookingSlot(slot,new Date("2026-09-01T00:00:00Z")),/requires_expiry/)});
test("agent cannot approve proposal and money uses safe minor units",()=>{const v:ProposalVersion={proposalId:"p",versionId:"v",version:1,currency:"MXN",subtotalMinor:10000,taxMinor:1600,totalMinor:11600,snapshot:{items:[]}};validateProposalVersion(v);assert.throws(()=>transitionProposal("pending_approval","approved",{actor:"agent",humanApprovalRecorded:true}),/human_approval_required/);assert.equal(transitionProposal("pending_approval","approved",{actor:"owner",humanApprovalRecorded:true}),"approved")});
test("accepted immutable proposal becomes project snapshot",()=>{const v:ProposalVersion={proposalId:"p",versionId:"v",version:2,currency:"MXN",subtotalMinor:10000,taxMinor:1600,totalMinor:11600,snapshot:{title:"Evento"}};const p=projectFromAcceptedProposal({tenantId:"t",leadId:"l",proposal:v,proposalStatus:"accepted"});assert.equal(p.confirmedTotalMinor,11600);assert.notEqual(p.proposalSnapshot,v.snapshot)});
test("outbox retries are bounded",async()=>{const event={tenantId:"t",eventId:"e",topic:"lead.created",idempotencyKey:"k",payload:{},attempts:1,maxAttempts:3};const r=await processOutboxEvent(event,{deliver:async()=>{throw new Error("down")}});assert.equal(r.status,"retry");const dead=await processOutboxEvent({...event,attempts:2},{deliver:async()=>{throw new Error("down")}});assert.equal(dead.status,"dead")});
