export type LegalBlock={kind:"h1"|"h2"|"p";text:string};
export const LEGAL_DOCS:Record<string,{title:string;blocks:LegalBlock[]}>={
"aviso-de-privacidad":{title:`Aviso de Privacidad`,blocks:[
{kind:"h1",text:`AVISO DE PRIVACIDAD INTEGRAL`},
{kind:"p",text:`2A VISUAL & SOUND LAB (en lo sucesivo identificado comercialmente como “`},
{kind:"p",text:`Dos2A”), con domicilio fiscal ubicado en Cedro 323 - 11, Col. Santa`},
{kind:"p",text:`María la Ribera, C.P. 06400, Alcaldía Cuauhtémoc, Ciudad de México, es el`},
{kind:"p",text:`responsable del tratamiento, uso y protección de sus datos personales, y al`},
{kind:"p",text:`respecto le informa lo siguiente:`},
{kind:"h2",text:`1. Datos Personales que Recopilamos`},
{kind:"p",text:`Para llevar a cabo las finalidades descritas en el presente Aviso de`},
{kind:"p",text:`Privacidad, recopilamos las siguientes categorías de datos personales:`},
{kind:"p",text:`-`},
{kind:"p",text:`Datos de identificación y contacto: Nombre completo, correo`},
{kind:"p",text:`electrónico, teléfono de contacto, ciudad y detalles del evento.`},
{kind:"p",text:`-`},
{kind:"p",text:`Datos de facturación y fiscales: Registro Federal de Contribuyentes`},
{kind:"p",text:`(RFC), Razón Social, Domicilio Fiscal, Régimen Fiscal y Uso de CFDI.`},
{kind:"h2",text:`2. Finalidades del Tratamiento de Datos Personales`},
{kind:"p",text:`Sus datos personales serán utilizados exclusivamente para las`},
{kind:"p",text:`siguientes finalidades`},
{kind:"p",text:`primarias, las cuales son necesarias para prestarle el servicio solicitado:`},
{kind:"p",text:`1.`},
{kind:"p",text:`Elaborar, enviar y dar seguimiento a cotizaciones de servicios`},
{kind:"p",text:`audiovisuales y producción de eventos.`},
{kind:"p",text:`2.`},
{kind:"p",text:`Formalizar la relación contractual y elaborar contratos de prestación de`},
{kind:"p",text:`servicios o arrendamiento de equipo.`},
{kind:"p",text:`3.`},
{kind:"p",text:`Coordinar la logística, montaje, operación y desmontaje en el sitio o`},
{kind:"p",text:`recinto de su evento.`},
{kind:"p",text:`4.`},
{kind:"p",text:`Emitir los Comprobantes Fiscales Digitales por Internet (CFDI/Facturas)`},
{kind:"p",text:`correspondientes.`},
{kind:"p",text:`5.`},
{kind:"p",text:`Gestionar procesos de cobro, pagos y administración del servicio.`},
{kind:"p",text:`Uso publicitario o secundario: Hacemos de su conocimiento que NO`},
{kind:"p",text:`utilizamos sus datos personales para finalidades secundarias de`},
{kind:"p",text:`mercadotecnia, publicidad, envío de boletines o prospección comercial no`},
{kind:"p",text:`solicitada.`},
{kind:"h2",text:`3. Transferencia de Datos Personales`},
{kind:"p",text:`2A VISUAL & SOUND LAB NO realiza transferencias de sus datos personales`},
{kind:"p",text:`a terceros, nacionales o extranjeros, ajenos a la organización. Sus datos`},
{kind:"p",text:`son tratados con estricta confidencialidad por nuestro personal autorizado`},
{kind:"p",text:`únicamente para el cumplimiento de las finalidades descritas.`},
{kind:"p",text:`(Se exceptúan únicamente los requerimientos de información formulados por`},
{kind:"p",text:`autoridades competentes en términos de la legislación aplicable).`},
{kind:"h2",text:`4. Ejercicio de Derechos ARCO y Revocación del Consentimiento`},
{kind:"p",text:`Usted tiene derecho a conocer qué datos personales tenemos de usted, para`},
{kind:"p",text:`qué los utilizamos y las condiciones del uso que les damos (Acceso).`},
{kind:"p",text:`Asimismo, es su derecho solicitar la corrección de su información personal`},
{kind:"p",text:`en caso de que esté desactualizada, sea inexacta o incompleta (`},
{kind:"p",text:`Rectificación); que la eliminemos de nuestros registros o bases de datos`},
{kind:"p",text:`cuando considere que la misma no está siendo utilizada adecuadamente (`},
{kind:"p",text:`Cancelación); así como oponerse al uso de sus datos personales para fines`},
{kind:"p",text:`específicos (Oposición). Estos derechos se conocen como Derechos ARCO.`},
{kind:"p",text:`Para el ejercicio de cualquiera de los Derechos ARCO, o para revocar el`},
{kind:"p",text:`consentimiento que nos haya otorgado para el tratamiento de sus datos,`},
{kind:"p",text:`usted deberá presentar la solicitud correspondiente enviando un correo`},
{kind:"p",text:`electrónico a la dirección:`},
{kind:"p",text:`📧 alanis@eventosdos2a.mx <alanis@eventosdos2a.mx>`},
{kind:"p",text:`Su solicitud deberá contener:`},
{kind:"p",text:`-`},
{kind:"p",text:`Nombre completo del titular y correo electrónico para recibir`},
{kind:"p",text:`notificaciones.`},
{kind:"p",text:`-`},
{kind:"p",text:`Documento oficial que acredite su identidad o representación legal.`},
{kind:"p",text:`-`},
{kind:"p",text:`Descripción clara y precisa de los datos personales respecto de los`},
{kind:"p",text:`cuales busca ejercer alguno de los derechos ARCO.`},
{kind:"p",text:`Atenderemos su solicitud en un plazo máximo de 20 (veinte) días hábiles`},
{kind:"p",text:`contados desde la fecha de recepción de la misma.`},
{kind:"h2",text:`5. Uso de Cookies y Tecnologías de Rastreo`},
{kind:"p",text:`Nuestro sitio web utiliza cookies y tecnologías de rastreo estándar`},
{kind:"p",text:`únicamente para asegurar el funcionamiento correcto del sitio y mejorar la`},
{kind:"p",text:`experiencia de navegación del usuario. Estas herramientas no recopilan`},
{kind:"p",text:`información personal sensible ni son utilizadas para perfiles publicitarios.`},
{kind:"h2",text:`6. Cambios al Aviso de Privacidad`},
{kind:"p",text:`El presente Aviso de Privacidad puede sufrir modificaciones, cambios o`},
{kind:"p",text:`actualizaciones derivadas de nuevos requerimientos legales o de nuestras`},
{kind:"p",text:`propias necesidades operativas. Cualquier modificación al presente aviso`},
{kind:"p",text:`estará disponible para su consulta en nuestro sitio web oficial.`},
{kind:"p",text:`Última actualización: Septiembre de 2026.`},
]},
"terminos-y-condiciones":{title:`Términos y Condiciones`,blocks:[
{kind:"h1",text:`TÉRMINOS Y CONDICIONES DE SERVICIO`},
{kind:"p",text:`El presente documento establece los Términos y Condiciones generales (en lo`},
{kind:"p",text:`sucesivo, los "Términos") bajo los cuales 2A VISUAL & SOUND LAB (en lo`},
{kind:"p",text:`sucesivo identificado comercialmente como “Dos2A”), con domicilio fiscal`},
{kind:"p",text:`en Cedro 323 - 11, Col. Santa María la Ribera, C.P. 06400, Alcaldía`},
{kind:"p",text:`Cuauhtémoc, Ciudad de México, presta servicios de producción audiovisual,`},
{kind:"p",text:`logística, operación y arrendamiento de equipo para eventos a sus Clientes.`},
{kind:"p",text:`Al solicitar una cotización, realizar el pago de un anticipo o firmar la`},
{kind:"p",text:`propuesta comercial correspondiente, el Cliente acepta de manera íntegra y`},
{kind:"p",text:`sin reserva los presentes Términos y Condiciones.`},
{kind:"h2",text:`1. Esquema de Pago y Facturación`},
{kind:"p",text:`-`},
{kind:"p",text:`Reserva de fecha: Para confirmar y apartar la fecha de un evento en la`},
{kind:"p",text:`agenda de Dos2A, el Cliente deberá cubrir un anticipo equivalente al 50%`},
{kind:"p",text:`(cincuenta por ciento) del monto total cotizado.`},
{kind:"p",text:`-`},
{kind:"p",text:`Liquidación del saldo: El 50% restante deberá ser liquidado a más`},
{kind:"p",text:`tardar el día del evento, previo al inicio de la operación o presentación`},
{kind:"p",text:`técnica.`},
{kind:"p",text:`-`},
{kind:"p",text:`Formas de pago aceptadas: Dos2A acepta pagos mediante transferencia`},
{kind:"p",text:`electrónica (SPEI), tarjetas de crédito/débito, depósitos bancarios y pago`},
{kind:"p",text:`en efectivo.`},
{kind:"p",text:`-`},
{kind:"p",text:`Facturación: Todos los servicios son facturables. En caso de requerir`},
{kind:"p",text:`Comprobante Fiscal Digital por Internet (CFDI), el Cliente deberá`},
{kind:"p",text:`proporcionar sus datos fiscales actualizados al momento de realizar su pago`},
{kind:"p",text:`o confirmar su servicio.`},
{kind:"h2",text:`2. Accesos, Permisos e Infraestructura del Recinto`},
{kind:"p",text:`-`},
{kind:"p",text:`Responsabilidad de acceso: El Cliente es el único responsable de`},
{kind:"p",text:`gestionar los permisos de ingreso, horarios de carga/descarga y acceso de`},
{kind:"p",text:`personal técnico con la administración del recinto o hotel contratado.`},
{kind:"p",text:`-`},
{kind:"p",text:`Infraestructura eléctrica y logística: El Cliente asume la total`},
{kind:"p",text:`responsabilidad por la idoneidad del lugar elegido. Dos2A no se hace`},
{kind:"p",text:`responsable por retrasos en el montaje o fallas en la ejecución derivadas`},
{kind:"p",text:`de:`},
{kind:"p",text:`-`},
{kind:"p",text:`Horarios restringidos o denegación de acceso al recinto.`},
{kind:"p",text:`-`},
{kind:"p",text:`Suministro eléctrico deficiente, variaciones de voltaje o falta de`},
{kind:"p",text:`capacidad instalada en el lugar.`},
{kind:"p",text:`-`},
{kind:"p",text:`Espacios físicos no adecuados o sin la ventilación/protección`},
{kind:"p",text:`requerida.`},
{kind:"p",text:`Cualquier retraso en el programa del evento ocasionado por estas causas`},
{kind:"p",text:`será responsabilidad exclusiva del Cliente.`},
{kind:"h2",text:`3. Eventos al Aire Libre, Clima y Fallas Ajenas`},
{kind:"p",text:`-`},
{kind:"p",text:`Protección contra intemperie: En eventos organizados al aire libre,`},
{kind:"p",text:`espacios abiertos o terrazas, el Cliente es responsable de proveer las`},
{kind:"p",text:`medidas de protección necesarias (carpas, techos o estructuras`},
{kind:"p",text:`impermeables) para resguardar la integridad del equipo de Dos2A.`},
{kind:"p",text:`-`},
{kind:"p",text:`Condiciones climáticas y apagones: Dos2A no asumirá responsabilidad`},
{kind:"p",text:`por la suspensión parcial o total del servicio atribuible a causas`},
{kind:"p",text:`climáticas (lluvia, viento extremo, tormentas) o cortes imprevistos en el`},
{kind:"p",text:`suministro eléctrico del recinto. Si las condiciones ambientales ponen en`},
{kind:"p",text:`riesgo el equipo o la seguridad del personal técnico, Dos2A se reserva`},
{kind:"p",text:`el derecho de pausar la operación hasta que existan condiciones seguras.`},
{kind:"h2",text:`4. Responsabilidad sobre el Equipo, Daños y Faltantes`},
{kind:"p",text:`-`},
{kind:"p",text:`Cuidado del equipamiento: Durante la estancia del equipo en las`},
{kind:"p",text:`instalaciones del evento, la custodia del mismo recae en el Cliente y/o la`},
{kind:"p",text:`administración del recinto.`},
{kind:"p",text:`-`},
{kind:"p",text:`Reparación y Reposición: En caso de daño parcial, mal uso por parte de`},
{kind:"p",text:`los asistentes, robo, extravío o destrucción total del equipo de Dos2A,`},
{kind:"p",text:`el Cliente (y en su caso, en corresponsabilidad con el recinto según el`},
{kind:"p",text:`contrato correspondiente) responderá por el costo total de reparación o`},
{kind:"p",text:`reposición a valor mercado de los equipos afectados, conforme a las`},
{kind:"p",text:`cláusulas estipuladas en el contrato de prestación de servicios firmado`},
{kind:"p",text:`previamente.`},
{kind:"h2",text:`5. Reprogramación y Cambios de Fecha`},
{kind:"p",text:`-`},
{kind:"p",text:`Cambio de fecha sin penalización: Si por razones operativas o`},
{kind:"p",text:`personales el Cliente requiere cambiar la fecha de su evento, Dos2A`},
{kind:"p",text:`respetará el 100% del anticipo pagado y lo aplicará a la nueva fecha,`},
{kind:"p",text:`sujeto a la disponibilidad del equipo y personal técnico en la agenda de la`},
{kind:"p",text:`empresa.`},
{kind:"h2",text:`6. Jurisdicción y Ley Aplicable`},
{kind:"p",text:`Para la interpretación y cumplimiento de los presentes Términos y`},
{kind:"p",text:`Condiciones, las partes se someten a la legislación federal vigente en los`},
{kind:"p",text:`Estados Unidos Mexicanos y a la jurisdicción de los tribunales competentes`},
{kind:"p",text:`de la Ciudad de México, renunciando expresamente a cualquier otro fuero que`},
{kind:"p",text:`por razón de sus domicilios presentes o futuros pudiera corresponderles.`},
]},
"politica-de-cancelacion":{title:`Política de Cancelación y Reembolsos`,blocks:[
{kind:"h1",text:`POLÍTICA DE CANCELACIÓN Y REEMBOLSOS`},
{kind:"p",text:`En 2A VISUAL & SOUND LAB (en lo sucesivo “Dos2A”), nuestro compromiso`},
{kind:"p",text:`es brindar certeza técnica y transparencia operativa en cada proyecto. La`},
{kind:"p",text:`presente Política regula los términos bajo los cuales el Cliente podrá`},
{kind:"p",text:`solicitar reprogramaciones, cancelaciones o reembolsos de los pagos`},
{kind:"p",text:`efectuados por concepto de apartado o contratación de nuestros servicios de`},
{kind:"p",text:`producción audiovisual.`},
{kind:"h2",text:`1. Anticipos y Aplicación de Pagos`},
{kind:"p",text:`-`},
{kind:"p",text:`El 50% de anticipo requerido para reservar la fecha en la agenda`},
{kind:"p",text:`operativa de Dos2A se abonará directamente a la cuenta total de la`},
{kind:"p",text:`factura o comprobante fiscal del servicio.`},
{kind:"p",text:`-`},
{kind:"p",text:`En caso de que el evento no pueda realizarse en la fecha originalmente`},
{kind:"p",text:`programada, el monto depositado no se pierde: este saldo a favor podrá`},
{kind:"p",text:`aplicarse íntegramente para la realización del evento en una nueva fecha,`},
{kind:"p",text:`sujeto a la disponibilidad de agenda y equipo de la empresa.`},
{kind:"h2",text:`2. Cancelaciones por Parte del Cliente`},
{kind:"p",text:`-`},
{kind:"p",text:`Cancelaciones con más de 30 días de anticipación: Si el Cliente`},
{kind:"p",text:`cancela el servicio formalmente y por escrito con más de 30 días naturales`},
{kind:"p",text:`de antelación a la fecha del evento, procederá el reembolso del monto`},
{kind:"p",text:`pagado, deduciendo únicamente los gastos administrativos o comisiones`},
{kind:"p",text:`bancarias aplicables.`},
{kind:"p",text:`-`},
{kind:"p",text:`Cancelaciones con menos de 30 días de anticipación: Si la cancelación`},
{kind:"p",text:`se realiza con poco tiempo de anticipación (30 días o menos previo al`},
{kind:"p",text:`evento), el dinero pagado no será devuelto en efectivo o transferencia,`},
{kind:"p",text:`pero quedará abonado como un saldo a favor que el Cliente podrá`},
{kind:"p",text:`utilizar para reagendar su evento en una fecha posterior.`},
{kind:"h2",text:`3. Imposibilidad de Prestación del Servicio por Causa Imputable a Dos2A`},
{kind:"p",text:`En el caso eventual de que Dos2A no pueda prestar el servicio por causas`},
{kind:"p",text:`directamente atribuibles a la empresa o fallas internas imprevistas,`},
{kind:"p",text:`nuestra prioridad será la reagendación del evento en mutuo acuerdo con el`},
{kind:"p",text:`Cliente, garantizando la misma calidad técnica y equipamiento contratado`},
{kind:"p",text:`sin costo adicional.`},
{kind:"h2",text:`4. Cancelación por Fuerza Mayor o Caso Fortuito`},
{kind:"p",text:`Si el evento debe cancelarse o suspenderse debido a causas ajenas a ambas`},
{kind:"p",text:`partes (tales como emergencias sanitarias, desastres naturales,`},
{kind:"p",text:`restricciones gubernamentales o condiciones climáticas extremas), se`},
{kind:"p",text:`aplicará la retención únicamente de los gastos operativos y logísticos ya`},
{kind:"p",text:`devengados por Dos2A hasta el momento de la cancelación (ej. transporte,`},
{kind:"p",text:`apartado de personal técnico o insumos no recuperables). El saldo restante`},
{kind:"p",text:`quedará a favor del Cliente para ser reprogramado.`},
{kind:"h2",text:`5. Plazos y Métodos para la Devolución de Fondos`},
{kind:"p",text:`En todos los casos donde proceda una devolución en dinero:`},
{kind:"p",text:`-`},
{kind:"p",text:`Las solicitudes deberán canalizarse a través del correo oficial:`},
{kind:"p",text:`alanis@eventosdos2a.mx`},
{kind:"p",text:`<alanis@eventosdos2a.mx>.`},
{kind:"p",text:`-`},
{kind:"p",text:`Los tiempos de acreditación del reembolso dependerán exclusivamente del`},
{kind:"p",text:`método de pago utilizado (transferencia SPEI, tarjeta de crédito o débito)`},
{kind:"p",text:`y de los tiempos de procesamiento de las instituciones bancarias`},
{kind:"p",text:`correspondientes. Dos2A emitirá el comprobante de dispersión en cuanto`},
{kind:"p",text:`la operación sea autorizada.`},
]},
};