"use client";
import Link from "next/link";import { ArrowRight } from "lucide-react";import { useLanguage } from "@/lib/language";import PublicShell from "./PublicShell";
const events=[
 {es:["Corporativos y congresos","Claridad de voz, contenido visible, tiempos controlados y una operación que acompaña el programa sin distraer del mensaje."],en:["Corporate events and conferences","Clear speech, visible content, controlled timing, and an operation that supports the program without distracting from the message."]},
 {es:["Lanzamientos y activaciones","Tecnología, iluminación y espacio físico trabajando juntos para que la marca se entienda y la experiencia se pueda vivir."],en:["Launches and activations","Technology, lighting, and physical space working together so the brand can be understood and experienced."]},
 {es:["Agencias y producciones","Nos integramos con alcance, responsables y tiempos definidos. La agencia mantiene el control creativo; dos A se responsabiliza de la ejecución técnica acordada."],en:["Agencies and productions","We join with defined scope, owners, and timing. The agency keeps creative control; dos A owns the agreed technical execution."]},
 {es:["Stands y exposiciones","Pantallas, iluminación, estructuras y elementos físicos coordinados para que el espacio funcione durante toda la jornada, no solo para la foto inicial."],en:["Stands and exhibitions","Screens, lighting, structures, and physical elements coordinated so the space works through the whole event, not only for the opening photo."]},
 {es:["Escenarios y experiencias en vivo","Audio, luz, video y operación coordinados para formatos que dependen del ritmo, la presencia y la respuesta del público."],en:["Stages and live experiences","Audio, light, video, and operation coordinated for formats driven by pace, presence, and audience response."]},
];
export default function EventsPage(){const{lang}=useLanguage();return <PublicShell><section className="page-hero"><p className="eyebrow">{lang==="es"?"Eventos":"Events"}</p><h1>{lang==="es"?"Producción técnica según el tipo de evento, no según un paquete genérico.":"Technical production based on the event, not a generic package."}</h1><p>{lang==="es"?"Cada formato tiene prioridades distintas. Empezamos por el objetivo, el espacio, el público y el programa antes de definir el equipo.":"Every format has different priorities. We start with the objective, venue, audience, and program before deciding what belongs in the plan."}</p></section><section className="section"><div className="event-list">{events.map((x,i)=><article key={i}><span>{String(i+1).padStart(2,"0")}</span><div><h2>{x[lang][0]}</h2><p>{x[lang][1]}</p></div></article>)}</div></section><section className="closing-cta"><h2>{lang==="es"?"Cuéntanos qué quieres producir.":"Tell us what you want to produce."}</h2><Link className="button button--light" href="/cotizar">{lang==="es"?"Cotizar mi evento":"Get a quote"}<ArrowRight size={17}/></Link></section></PublicShell>}
