export type SiteLang = "es" | "en";

type Bilingual = { es: string; en: string };

export const siteContent = {
  brand: {
    name: "dos A",
    tagline: { es: "audio · iluminación · video", en: "audio · lighting · video" } as Bilingual,
    whatsapp: "525500000000",
    email: "2audioiluminacion@gmail.com",
  },
  nav: {
    home: { es: "Inicio", en: "Home" },
    services: { es: "Servicios", en: "Services" },
    events: { es: "Eventos", en: "Events" },
    portfolio: { es: "Portafolio", en: "Portfolio" },
    signal: { es: "dos A Señal", en: "dos A Signal" },
    quote: { es: "Cotizar", en: "Get a quote" },
    contact: { es: "Contacto", en: "Contact" },
  },
  contact: {
    eyebrow: { es: "Contacto", en: "Contact" },
    title: { es: "Hablemos de tu evento.", en: "Let's talk about your event." },
    intro: { es: "Elige el canal que te quede más cómodo. Respondemos con un alcance claro, no con un guion de ventas.", en: "Pick whichever channel suits you. We reply with a clear scope, not a sales script." },
    waTitle: { es: "WhatsApp", en: "WhatsApp" },
    waBody: { es: "La vía más rápida para una primera conversación. Cuéntanos qué evento tienes en puerta.", en: "The fastest way to start a conversation. Tell us about your upcoming event." },
    waCta: { es: "Abrir WhatsApp", en: "Open WhatsApp" },
    waMessage: { es: "Hola dos A, tengo un evento en puerta y quiero cotizar: ", en: "Hi dos A, I have an event coming up and I'd like a quote: " },
    mailTitle: { es: "Correo", en: "Email" },
    mailBody: { es: "Para briefs, propuestas y archivos. Todo queda por escrito.", en: "For briefs, proposals, and files. Everything in writing." },
    quoteTitle: { es: "Cotización", en: "Quote" },
    quoteBody: { es: "Si ya sabes lo que necesitas, el formulario te toma dos minutos.", en: "If you already know what you need, the form takes two minutes." },
    quoteCta: { es: "Ir al formulario", en: "Go to the form" },
    location: { es: "Ciudad de México · proyectos en todo México", en: "Mexico City · projects across Mexico" },
  },
  servicePageLabels: {
    includes: { es: "Qué incluye", en: "What's included" },
    equipment: { es: "Equipo", en: "Equipment" },
    projects: { es: "Proyectos con este servicio", en: "Projects using this service" },
    faq: { es: "Preguntas frecuentes", en: "Frequently asked questions" },
    moreProjects: { es: "Ver portafolio completo", en: "See full portfolio" },
  },
  servicePages: {
    audio: {
      name: { es: "Audio", en: "Audio" },
      n: "01",
      h1: { es: "Audio que se entiende en cada asiento.", en: "Sound that's understood in every seat." },
      support: { es: "Sonido y microfonía dimensionados al espacio, el aforo y el programa. No un paquete genérico.", en: "Sound and microphones sized to the venue, the audience, and the program. Not a generic package." },
      cta: { es: "Cotizar audio", en: "Quote audio" },
      waMessage: { es: "Hola dos A, necesito cotizar audio para un evento: ", en: "Hi dos A, I need an audio quote for an event: " },
      facts: [
        { es: "+15 años operando", en: "15+ years operating" },
        { es: "Operador incluido", en: "Operator included" },
        { es: "CDMX · todo México", en: "CDMX · all of Mexico" },
      ],
      includes: [
        { es: "Sistema de sonido dimensionado al venue", en: "Sound system sized to the venue" },
        { es: "Microfonía inalámbrica: solapa, diadema y mano", en: "Wireless microphones: lapel, headset, and handheld" },
        { es: "Mezcla y operación en vivo incluidas", en: "Live mixing and operation included" },
        { es: "Monitoreo de escenario y de sala", en: "Stage and room monitoring" },
        { es: "Prueba de sonido antes del evento", en: "Sound check before the event" },
      ],
      brands: ["JBL", "QSC", "Shure", "Sennheiser"],
      faq: [
        { q: { es: "¿Con cuánta anticipación reservo el audio?", en: "How far ahead should I book audio?" }, a: { es: "Para eventos medianos, mínimo dos o tres semanas. Para producciones grandes, de cuatro a ocho. Si tu fecha es más cercana, pregúntanos: a veces el calendario lo permite.", en: "For mid-size events, at least two to three weeks. For large productions, four to eight. If your date is closer, ask us: sometimes the calendar allows it." } },
        { q: { es: "¿El operador va incluido?", en: "Is the operator included?" }, a: { es: "Sí. Todo alcance de audio incluye técnico operador durante el evento. El equipo no se entrega solo.", en: "Yes. Every audio scope includes an operating technician during the event. Equipment never goes out alone." } },
        { q: { es: "¿Cubren eventos al aire libre?", en: "Do you cover outdoor events?" }, a: { es: "Sí. Dimensionamos potencia y protección según el espacio y las condiciones del venue.", en: "Yes. We size power and protection to the space and the venue's conditions." } },
      ],
      photos: ["/images/projects/dosa-recovered-audio-video.webp", "/images/projects/dosa-recovered-hero-scale.webp"],
      closing: { es: "¿Tu evento necesita sonido?", en: "Does your event need sound?" },
    },
    iluminacion: {
      name: { es: "Iluminación", en: "Lighting" },
      n: "02",
      h1: { es: "La luz que convierte un espacio en escenario.", en: "Light that turns a space into a stage." },
      support: { es: "Iluminación escénica, ambiental y arquitectónica diseñada alrededor del espacio, la cámara y los momentos clave.", en: "Stage, ambient, and architectural lighting designed around the space, the camera, and the key moments." },
      cta: { es: "Cotizar iluminación", en: "Quote lighting" },
      waMessage: { es: "Hola dos A, necesito cotizar iluminación para un evento: ", en: "Hi dos A, I need a lighting quote for an event: " },
      facts: [
        { es: "Diseño previo incluido", en: "Design included upfront" },
        { es: "Operación en vivo", en: "Live operation" },
        { es: "CDMX · todo México", en: "CDMX · all of Mexico" },
      ],
      includes: [
        { es: "Plano lumínico según el venue y el programa", en: "Lighting plan based on the venue and program" },
        { es: "Moving heads, wash y luces de efecto", en: "Moving heads, wash, and effect lights" },
        { es: "Barras LED e iluminación arquitectónica", en: "LED bars and architectural lighting" },
        { es: "Sincronización con música y momentos del programa", en: "Sync with music and program cues" },
        { es: "Operador de iluminación durante el evento", en: "Lighting operator during the event" },
      ],
      brands: ["Moving heads", "Wash", "Barras LED", "Control DMX"],
      faq: [
        { q: { es: "¿Hacen el diseño antes de cotizar?", en: "Do you design before quoting?" }, a: { es: "Proponemos el planteamiento lumínico junto con la propuesta, a partir del espacio y lo que quieres lograr.", en: "We propose the lighting approach with the quote, based on the space and what you want to achieve." } },
        { q: { es: "¿Se sincroniza con el DJ o la música?", en: "Does it sync with the DJ or music?" }, a: { es: "Sí. Programamos escenas y sincronización según el programa: ambientación, peaks y momentos clave.", en: "Yes. We program scenes and sync to the program: ambience, peaks, and key moments." } },
        { q: { es: "¿Funciona en eventos de día?", en: "Does it work for daytime events?" }, a: { es: "Sí, dimensionando potencia y posiciones a la luz ambiental. En exteriores diurnos la prioridad cambia y te lo decimos con honestidad.", en: "Yes, sizing power and positions to the ambient light. For daytime outdoor events priorities change and we tell you honestly." } },
      ],
      photos: ["/images/projects/led-sculpture-1181w.webp", "/images/projects/dosa-recovered-hero-scale.webp"],
      closing: { es: "¿Tu espacio necesita luz escénica?", en: "Does your space need stage light?" },
    },
    video: {
      name: { es: "Video y pantallas", en: "Video and screens" },
      n: "03",
      h1: { es: "Pantallas que se ven desde la última fila.", en: "Screens visible from the last row." },
      support: { es: "Pantallas LED, proyección, monitores y señal coordinados con tu contenido y tu programa.", en: "LED screens, projection, displays, and signal coordinated with your content and your program." },
      cta: { es: "Cotizar video", en: "Quote video" },
      waMessage: { es: "Hola dos A, necesito cotizar pantallas o video para un evento: ", en: "Hi dos A, I need a screens/video quote for an event: " },
      facts: [
        { es: "Pitch según distancia", en: "Pitch matched to distance" },
        { es: "Técnicos en sitio", en: "Technicians on site" },
        { es: "CDMX · todo México", en: "CDMX · all of Mexico" },
      ],
      includes: [
        { es: "Pantalla LED con el pitch correcto para tu aforo", en: "LED wall with the right pitch for your audience" },
        { es: "Proyección y monitores de apoyo", en: "Projection and support displays" },
        { es: "Switcher, procesadores y distribución de señal", en: "Switcher, processors, and signal distribution" },
        { es: "Apoyo a contenidos, formatos y playback", en: "Content, format, and playback support" },
        { es: "Video mapping como requerimiento especial", en: "Video mapping as a special requirement" },
      ],
      brands: ["Pantallas LED", "Proyección", "Monitores", "Video mapping"],
      faq: [
        { q: { es: "¿Qué tamaño de pantalla necesito?", en: "What screen size do I need?" }, a: { es: "Depende de la distancia del público y el contenido. Calculamos tamaño y pitch en la propuesta, no a ciegas.", en: "It depends on audience distance and content. We calculate size and pitch in the proposal, never blind." } },
        { q: { es: "¿Ayudan con los contenidos?", en: "Do you help with content?" }, a: { es: "Sí. Revisamos formatos, resoluciones y playback antes del evento para que nada falle en pantalla.", en: "Yes. We check formats, resolutions, and playback before the event so nothing fails on screen." } },
        { q: { es: "¿Hacen video mapping?", en: "Do you do video mapping?" }, a: { es: "Sí, como requerimiento especial: se evalúa superficie, luz ambiental y contenido en la propuesta.", en: "Yes, as a special requirement: surface, ambient light, and content are evaluated in the proposal." } },
      ],
      photos: ["/images/projects/mobil-hologram-1920w.webp", "/images/projects/dosa-recovered-audio-video.webp"],
      closing: { es: "¿Tu mensaje necesita pantalla?", en: "Does your message need a screen?" },
    },
    escenarios: {
      name: { es: "Escenarios y stands", en: "Stages and stands" },
      n: "04",
      h1: { es: "Estructuras que se ven y aguantan.", en: "Structures that look good and hold up." },
      support: { es: "Escenarios, stands y escenografía coordinados con pantallas, iluminación, branding y operación.", en: "Stages, stands, and scenic environments coordinated with screens, lighting, branding, and operation." },
      cta: { es: "Cotizar escenario", en: "Quote stage" },
      waMessage: { es: "Hola dos A, necesito cotizar un escenario o stand: ", en: "Hi dos A, I need a quote for a stage or stand: " },
      facts: [
        { es: "Diseño según venue", en: "Design matched to venue" },
        { es: "Montaje y desmontaje", en: "Setup and teardown" },
        { es: "CDMX · todo México", en: "CDMX · all of Mexico" },
      ],
      includes: [
        { es: "Diseño según espacio, aforo y brief", en: "Design based on space, audience, and brief" },
        { es: "Tarimas, estructuras y acabados", en: "Platforms, structures, and finishes" },
        { es: "Branding e impresión integrados", en: "Integrated branding and print" },
        { es: "Coordinación con audio, video e iluminación", en: "Coordination with audio, video, and lighting" },
        { es: "Montaje y desmontaje con tiempos definidos", en: "Setup and teardown with defined timing" },
      ],
      brands: ["Stands", "Escenografía", "Tarimas", "Branding"],
      faq: [
        { q: { es: "¿Hacen diseño personalizado?", en: "Do you do custom design?" }, a: { es: "Sí. Partimos del brief y del espacio, y proponemos estructura, acabados y branding en la propuesta.", en: "Yes. We start from the brief and the space, and propose structure, finishes, and branding in the proposal." } },
        { q: { es: "¿Trabajan en expos y congresos?", en: "Do you work at expos and conferences?" }, a: { es: "Sí. Coordinamos con el organizador los tiempos de montaje, reglas del recinto y entrega del stand.", en: "Yes. We coordinate build times, venue rules, and stand handover with the organizer." } },
        { q: { es: "¿Cuánto toma el montaje?", en: "How long does setup take?" }, a: { es: "Depende del tamaño y el recinto. Los tiempos de montaje y desmontaje quedan definidos por escrito en la propuesta.", en: "It depends on size and venue. Setup and teardown times are defined in writing in the proposal." } },
      ],
      photos: ["/images/projects/dosa-recovered-stand-exhibition.webp", "/images/projects/dosa-recovered-experiential-entry.webp"],
      closing: { es: "¿Tu marca necesita un escenario?", en: "Does your brand need a stage?" },
    },
  },
  hero: {
    eyebrow: {
      es: "Producción técnica para empresas, agencias y organizadores de eventos.",
      en: "Technical production for companies, agencies, and event organizers.",
    },
    title: {
      es: "Audio, video, iluminación y operación. Un solo equipo.",
      en: "Audio, video, lighting, and technical operation. One team.",
    },
    support: {
      es: "Diseñamos, coordinamos y operamos congresos, lanzamientos, activaciones, stands y experiencias de marca en Ciudad de México y proyectos en todo México.",
      en: "We design, coordinate, and operate conferences, launches, activations, stands, and brand experiences from Mexico City, with projects across Mexico.",
    },
    primary: { es: "Cotizar mi evento", en: "Get a quote" },
    secondary: { es: "Ver producciones", en: "See productions" },
    proof: { es: "Más de 15 años de experiencia.", en: "More than 15 years of experience." },
  },
  clients: {
    eyebrow: { es: "Confían en dos A", en: "Trusted by dos A" },
    names: ["Coca-Cola", "ExxonMobil", "Chevron", "J.P. Morgan", "L'Oréal", "Viajes El Corte Inglés"],
    government: { es: "CONACYT · CONAVI · IFT · CONAPRED", en: "CONACYT · CONAVI · IFT · CONAPRED" },
    note: { es: "y dependencias del sector público", en: "and public-sector organizations" },
  },
  journey: [
    {
      id: "scale",
      eyebrow: { es: "Producción técnica integral", en: "Integrated technical production" },
      title: { es: "Una producción. Un equipo responsable de que todo funcione.", en: "One production. One team accountable for making it work." },
      body: { es: "Audio, video, iluminación y operación coordinados desde el principio.", en: "Audio, video, lighting, and technical operation coordinated from the start." },
      image: "/images/projects/mobil-hologram-1920w.webp",
      alt: { es: "Holograma de gran formato en experiencia de marca Mobil", en: "Large-format hologram at a Mobil brand experience" },
      position: "center 48%",
      mobilePosition: "58% center",
    },
    {
      id: "audio-video",
      eyebrow: { es: "Audio + video", en: "Audio + video" },
      title: { es: "Que todos escuchen. Que todos vean. Que el mensaje llegue.", en: "Make sure they hear it. See it. Understand it." },
      body: { es: "Sistemas, pantallas, contenido y operación definidos alrededor del espacio y del público.", en: "Sound, screens, content, and operation planned around the space and audience." },
      image: "/images/projects/dosa-recovered-audio-video.webp",
      alt: { es: "Evento con múltiples pantallas y producción audiovisual", en: "Event with multiple screens and audiovisual production" },
      position: "center center",
      mobilePosition: "52% center",
    },
    {
      id: "lighting",
      eyebrow: { es: "Iluminación", en: "Lighting" },
      title: { es: "La atmósfera también se diseña.", en: "Atmosphere is designed, too." },
      body: { es: "La luz organiza el espacio, dirige la mirada y cambia cómo se siente un momento.", en: "Light organizes the space, guides attention, and changes how a moment feels." },
      image: "/images/projects/led-sculpture-1181w.webp",
      alt: { es: "Escultura LED con video mapping diseñada por dos A", en: "LED sculpture with video mapping designed by dos A" },
      position: "center center",
      mobilePosition: "54% center",
    },
    {
      id: "stands",
      eyebrow: { es: "Escenarios + stands", en: "Stages + stands" },
      title: { es: "Del escenario al espacio completo.", en: "From the stage to the whole space." },
      body: { es: "Estructura, pantallas, iluminación y marca coordinadas como una sola experiencia física.", en: "Structure, screens, lighting, and brand elements coordinated as one physical experience." },
      image: "/images/projects/dosa-recovered-stand-exhibition.webp",
      alt: { es: "Stand de exposición de gran formato", en: "Large exhibition stand" },
      position: "center center",
      mobilePosition: "50% center",
    },
    {
      id: "experiences",
      eyebrow: { es: "Experiencias", en: "Experiences" },
      title: { es: "No entregamos piezas aisladas. Construimos experiencias completas.", en: "We do not deliver isolated pieces. We build complete experiences." },
      body: { es: "Cuando el proyecto lo pide, la tecnología, el espacio y la interacción trabajan juntos.", en: "When the project calls for it, technology, space, and interaction work together." },
      image: "/images/projects/dosa-recovered-experiential-entry.webp",
      alt: { es: "Entrada iluminada para una experiencia de marca", en: "Illuminated entrance for a brand experience" },
      position: "center center",
      mobilePosition: "center center",
    },
    {
      id: "operation",
      eyebrow: { es: "Operación", en: "Operation" },
      title: { es: "El evento empieza antes de que llegue el público.", en: "The event starts before the audience arrives." },
      body: { es: "Alcance claro, pruebas, montaje y operación para llegar al momento importante con responsabilidades definidas.", en: "Clear scope, testing, setup, and operation so responsibilities are defined before the important moment." },
      image: "/images/hero/dosa-hero-loreal-1920w.webp",
      alt: { es: "Gala corporativa L'Oréal Luxe con producción integral de dos A", en: "L'Oréal Luxe corporate gala with full production by dos A" },
      position: "center center",
      mobilePosition: "54% center",
    },
  ],
  audience: {
    title: { es: "Una forma de trabajar para proyectos donde la coordinación importa.", en: "A way of working for projects where coordination matters." },
    items: [
      { title: { es: "Empresas", en: "Companies" }, body: { es: "Congresos, reuniones, lanzamientos, convenciones y eventos internos donde el mensaje y la operación no pueden fallar.", en: "Conferences, meetings, launches, conventions, and internal events where message and operation both matter." } },
      { title: { es: "Agencias y productores", en: "Agencies and producers" }, body: { es: "Nos integramos a una producción mayor, respetamos el concepto creativo y nos hacemos responsables del alcance técnico acordado.", en: "We join a larger production, respect the creative concept, and own the agreed technical scope." } },
      { title: { es: "Marcas y activaciones", en: "Brands and activations" }, body: { es: "Pantallas, iluminación, stands, escenarios y experiencias para convertir una idea de marca en un espacio real.", en: "Screens, lighting, stands, stages, and experiences that turn a brand idea into a real space." } },
    ],
  },
  services: {
    title: { es: "La parte técnica de tu evento, coordinada de principio a fin.", en: "The technical side of your event, coordinated from start to finish." },
    intro: { es: "Podemos encargarnos de una necesidad específica o coordinar varias disciplinas como un solo equipo.", en: "We can handle one defined need or coordinate several disciplines as one team." },
    items: [
      { title: { es: "Audio", en: "Audio" }, body: { es: "Sonido y microfonía para voz, música, presentaciones y formatos híbridos según el espacio, aforo y dinámica.", en: "Sound and microphones for speech, music, presentations, and hybrid formats based on venue, audience, and flow." } },
      { title: { es: "Video y pantallas", en: "Video and screens" }, body: { es: "Pantallas LED, proyección, monitores, señal y apoyo a contenidos para presentaciones, escenarios, stands y experiencias.", en: "LED screens, projection, displays, signal, and content support for presentations, stages, stands, and experiences." } },
      { title: { es: "Iluminación", en: "Lighting" }, body: { es: "Iluminación escénica, ambiental y arquitectónica diseñada alrededor del espacio, la cámara y los momentos clave.", en: "Stage, ambient, and architectural lighting planned around the space, camera, and key moments." } },
      { title: { es: "Escenarios, stands y escenografía", en: "Stages, stands, and scenic environments" }, body: { es: "Estructuras y elementos físicos coordinados con pantallas, iluminación, branding y necesidades operativas.", en: "Physical structures and scenic elements coordinated with screens, lighting, branding, and operational needs." } },
      { title: { es: "Operación y coordinación", en: "Operation and coordination" }, body: { es: "Tiempos, montaje, pruebas, operación y desmontaje de nuestro alcance técnico con responsabilidades claras.", en: "Timing, setup, testing, operation, and teardown for our technical scope with clear responsibilities." } },
      { title: { es: "Requerimientos especiales", en: "Special requirements" }, body: { es: "Según el proyecto: traducción simultánea, cómputo, efectos, mapping, fotografía, grabación y otros requerimientos confirmados en la propuesta.", en: "Depending on the project: interpretation, computers, effects, mapping, photography, recording, and other requirements confirmed in the proposal." } },
    ],
  },
  process: {
    title: { es: "Cuéntanos qué quieres lograr. Nosotros aterrizamos la parte técnica.", en: "Tell us what you need to accomplish. We define the technical scope." },
    steps: [
      { n: "01", title: { es: "Cuéntanos tu evento", en: "Tell us about the event" }, body: { es: "Fecha, lugar, público, objetivo y lo que ya tienes definido.", en: "Date, venue, audience, objective, and what is already defined." } },
      { n: "02", title: { es: "Aterrizamos el alcance", en: "We define the scope" }, body: { es: "Identificamos qué necesita audio, video, iluminación, escenario, stand u operación.", en: "We identify what needs audio, video, lighting, staging, stands, or technical operation." } },
      { n: "03", title: { es: "Preparamos la propuesta", en: "We prepare the proposal" }, body: { es: "Presentamos el alcance y ajustamos lo necesario antes de confirmar.", en: "We present the scope and refine what is needed before confirmation." } },
      { n: "04", title: { es: "Producimos y operamos", en: "We produce and operate" }, body: { es: "Coordinamos montaje, pruebas, operación y desmontaje según el proyecto.", en: "We coordinate setup, testing, operation, and teardown for the project." } },
    ],
  },
  genio: {
    eyebrow: { es: "Brief del evento", en: "Event brief" },
    title: { es: "¿Todavía no sabes exactamente qué necesitas?", en: "Not sure exactly what you need yet?" },
    body: { es: "Cuéntanos la fecha, el lugar y la idea con tus propias palabras. Ordenaremos lo esencial para preparar el siguiente paso sin pedirte que conozcas términos técnicos.", en: "Share the date, place, and idea in your own words. We will organize the essentials for the next step without making you learn technical terms." },
    cta: { es: "Preparar mi brief", en: "Prepare my brief" },
  },
  quote: {
    title: { es: "Cuéntanos tu evento. Empecemos por lo esencial.", en: "Tell us about your event. Start with what you know." },
    body: { es: "No necesitas saber qué equipo pedir. Danos el contexto y te ayudamos a ordenar el alcance.", en: "You do not need to know which equipment to request. Give us the context and we will help organize the scope." },
  },
};
